timeout: 20
triggers:
  - name: github
    type: github_pr
    runs:
      - name: checkpatch
        container: us.gcr.io/ltd-heracles-dev/zephyr-builder
        script: checkpatch
        params: {}
      - name: sanity
        container: us.gcr.io/ltd-heracles-dev/zephyr-builder
        script: sanity
        params:
          PLATFORMS: frdm_k64f 96b_nitrogen 96b_carbon qemu_cortex_m3
      - name: compile-qemu_cortex_m3-helloworld
        container: us.gcr.io/ltd-heracles-dev/zephyr-builder
        script: compile
        params:
          BOARD: qemu_cortex_m3
          APP: samples/hello_world/
        triggers:
          - name: qemu-test
      - name: compile-frdm_k64f-msgqapi
        container: us.gcr.io/ltd-heracles-dev/zephyr-builder
        script: compile
        params:
          BOARD: frdm_k64f
          APP: tests/kernel/msgq/msgq_api
        triggers:
          - name: lava-test
  - name: qemu-test
    type: github_pr
    runs:
      - name: qemu-cortex-m3
        container: us.gcr.io/ltd-heracles-dev/zephyr-builder
        script: qemu-test
  - name: lava-test
    type: lava_zephyr_pr
    runs:
      - name: lava-frdm_k64f
        container: us.gcr.io/ltd-heracles-dev/zephyr-builder
        script: lava-test
params:
  GH_PRNUM: SET_BY_TRIGGER
  GH_OWNER: SET_BY_TRIGGER
  GH_REPO: SET_BY_TRIGGER
  GIT_LOCAL: /srv/repos/zephyr/

scripts:
  checkpatch: |
    #!/bin/sh -ex
    git format-patch $GIT_SHA_BASE..$GIT_SHA
    # if you have file 1.patch, 2.patch, 3.patch, checkpatch.pl has a bug that
    # will cause it to exit(0) if 1.patch or 2.patch is a good patch and never
    # test the rest of the patches. sooo....
    for x in *.patch ; do
      ./scripts/checkpatch.pl $x
    done

  sanity: |
    #!/bin/bash -ex
    source ./zephyr-env.sh
    mkdir -p outdir
    for x in `echo $PLATFORMS | sed -e 's/ /\n/g'` ; do
      echo == $(date "+%F %T") sanity checking $x ...
      time sanitycheck \
        --platform $x \
        --inline-logs \
        --build-only \
        --outdir outdir \
        --no-clean \
        --enable-slow \
        --testcase-root=tests/ \
        -j 8 || exit 1
    done

  compile: |
    #!/bin/sh -ex
    cd $APP
    make
    cp outdir/$BOARD/zephyr.* /archive

  qemu-test: |
    #!/bin/sh -ex
    wget -O zephyr.elf ${H_TRIGGER_URL}zephyr.elf
    timeout 15s qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -vga none -kernel zephyr.elf > /archive/qemu.log || /bin/true
    grep "Hello World! arm" /archive/qemu.log

  lava-test: "UNUSED BY lava-zephyr"
